#!/usr/bin/perl

use strict;
use warnings;

use POSIX qw(strftime);
use Getopt::Long;

my $prefix = '/var/log/ibd/';
my $file;
my $oldfile;

GetOptions('p|prefix=s', \$prefix)
    or die("invalid options: $!");

mkdir($prefix) unless -e $prefix;

while (<>) {
    my @t = gmtime(time());
    my $time = POSIX::strftime("%Y%m%d", @t);
    my $file = $prefix . '/' . $time . '.log';

    chomp($_);

    if (open(my $FILE, ">> $file")) {
        print($FILE POSIX::strftime("%Y%m%dT%H%M%S: ", @t));
        print($FILE $_."\n");
        close($FILE);
    }
}
